apiVersion: apps/v1
kind: Deployment
metadata:
  name: synchnotes-1
  labels:
    app: synchnotes-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: synchnotes-1
  template:
    metadata:
      labels:
        app: synchnotes-1
    spec:
      containers:
      - name: synchnotes-1
        image: 161272974421.dkr.ecr.us-east-1.amazonaws.com/synchnotes:75
        ports:
        - containerPort: 3000